#!/usr/bin/env python3
# SPDX-License-Identifier: MulanPSL-2.0
"""fire_detect driver -- fire & smoke detection RoboNIX primitive (MCP handler layer).

Capabilities are exposed via **MCP**, using the
``fire_detect_mcp`` / ``std_msgs_mcp`` dataclasses generated by ``rbnx codegen --mcp``.

Capability surface:
  robonix/service/fire_detect/fire_detect    rpc  detect fire & smoke in the frame (attach GPS on a hit), single frame
  robonix/service/fire_detect/start_monitor  rpc  start the real-time monitor (background continuous frame inference)
  robonix/service/fire_detect/stop_monitor   rpc  stop the real-time monitor
  robonix/service/fire_detect/monitor_state  rpc  read the monitor's latest result (for polling by an external loop)

This file is SDK-agnostic: it only calls the semantic methods of ``fire_detect.backend.FireDetectBackend``,
and contains no MSDK/HTTP terminology. Swap the camera/SDK by swapping only the backend.
"""
from __future__ import annotations

import json
import os
from typing import Any

from robonix_api import Service, Ok  # type: ignore

from .backend import FireDetectBackend
from .stream import AnnotatedStreamer

# -- import the codegen-generated MCP dataclasses --
# generated by `rbnx codegen -p . --out-dir rbnx-build/codegen --mcp` into
# rbnx-build/codegen/robonix_mcp_types/.
import fire_detect_mcp  # noqa: E402
import std_msgs_mcp  # noqa: E402

detector = Service(id="fire_detect", namespace="robonix/service/fire_detect")

_backend: FireDetectBackend | None = None
_streamer: AnnotatedStreamer | None = None


def _get_backend() -> FireDetectBackend:
    global _backend
    if _backend is None:
        host = os.environ.get("RC_PRO_IP", "172.20.10.3")
        port = int(os.environ.get("RC_PRO_PORT", "8080"))
        _backend = FireDetectBackend(host, port)
    return _backend


def _status(result) -> std_msgs_mcp.String:
    """Serialize a dict result into the std_msgs/String response field."""
    return std_msgs_mcp.String(data=json.dumps(result, ensure_ascii=False))


# ═══════════════════════════════════════════════════════════════════════════════
# fire & smoke detection
# ═══════════════════════════════════════════════════════════════════════════════

@detector.mcp("robonix/service/fire_detect/fire_detect")
def fire_detect(req: fire_detect_mcp.FireDetect_Request) -> fire_detect_mcp.FireDetect_Response:
    """Detect fire & smoke (flame/smoke) in the current frame, attaching the current GPS coordinates on a hit."""
    conf = float(req.min_confidence) if req.min_confidence > 0 else None
    result = _get_backend().detect(min_confidence=conf)
    return fire_detect_mcp.FireDetect_Response(status=_status(result))


# ═══════════════════════════════════════════════════════════════════════════════
# real-time monitor (background continuous frame inference, polled by an external loop)
# ═══════════════════════════════════════════════════════════════════════════════

@detector.mcp("robonix/service/fire_detect/start_monitor")
def start_monitor(_req: fire_detect_mcp.StartMonitor_Request) -> fire_detect_mcp.StartMonitor_Response:
    """Start the real-time fire & smoke monitor: a background thread keeps grabbing frames and inferring; the latest result is polled via monitor_state."""
    result = _get_backend().start_monitor()
    return fire_detect_mcp.StartMonitor_Response(status=_status(result))


@detector.mcp("robonix/service/fire_detect/stop_monitor")
def stop_monitor(_req: fire_detect_mcp.StopMonitor_Request) -> fire_detect_mcp.StopMonitor_Response:
    """Stop the real-time fire & smoke monitor."""
    result = _get_backend().stop_monitor()
    return fire_detect_mcp.StopMonitor_Response(status=_status(result))


@detector.mcp("robonix/service/fire_detect/monitor_state")
def monitor_state(_req: fire_detect_mcp.MonitorState_Request) -> fire_detect_mcp.MonitorState_Response:
    """Read the real-time monitor's latest result (alert/detections/gps/timestamp)."""
    result = _get_backend().monitor_state()
    return fire_detect_mcp.MonitorState_Response(status=_status(result))


# ═══════════════════════════════════════════════════════════════════════════════
# Lifecycle
# ═══════════════════════════════════════════════════════════════════════════════

@detector.on_init
def init(config: dict | None) -> Any:
    """Initialize the backend on startup and probe the RC Pro connection."""
    global _backend, _streamer
    cfg = config or {}
    host = cfg.get("rc_pro_ip") or os.environ.get("RC_PRO_IP", "172.20.10.3")
    port = int(cfg.get("rc_pro_port") or os.environ.get("RC_PRO_PORT", "8080"))
    model_path = cfg.get("model_path", "") or os.environ.get("FIRE_MODEL_PATH", "")
    min_conf = float(cfg.get("min_confidence", 0.4))
    _backend = FireDetectBackend(host, port, model_path=model_path, min_confidence=min_conf)
    if not _backend.ping().get("success"):
        print(f"[fire_detect] ⚠ cannot connect to RC Pro ({host}:{port}); will still register but calls may fail", flush=True)
    else:
        print(f"[fire_detect] ✅ connected to RC Pro ({host}:{port})", flush=True)

    # real-time visualization: start the web annotated stream together with the primitive (draws boxes as it detects, for web/app viewing)
    stream_port = int(cfg.get("stream_port", 8081))
    _streamer = AnnotatedStreamer(_backend, conf=min_conf, port=stream_port)
    _streamer.start()
    return Ok()


@detector.on_shutdown
def shutdown() -> Any:
    """Clean up on shutdown: stop the monitor thread first, then tear down the backend."""
    global _backend, _streamer
    if _streamer is not None:
        _streamer.stop()
        _streamer = None
    if _backend is not None:
        _backend.stop_monitor()
    _backend = None
    return Ok()


# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    detector.run()
